# Generated by Django 2.2.13 on 2022-12-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallery',
            new_name='image',
        ),
    ]
