# Generated by Django 2.2.13 on 2022-12-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20221208_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('paragraph', models.CharField(max_length=50)),
                ('slide', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
